### Editar un ticket (PUT)

PUT http://localhost:5000/tickets/4 
Content-Type: application/json

{
  "title": "Ticket actualizado",
  "description": "Nueva descripción actualizada",
  "status": "In Progress",
  "category_id": 2
}